local_backend:
  url: http://localhost:8081/api/v1
backend:
  name: git-gateway
  branch: main

media_folder: "images"

collections:
  - name: "content"
    label: "Website Content"
    files:
      - name: "content"
        label: "Main Content"
        file: "_data/content.json"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Uitnodiging", name: "uitnodiging", widget: "string" }
          - {
              label: "Introductie tekst",
              name: "what_is_hat",
              widget: "markdown",
            }
          - { label: "Oorsprong titel", name: "origin_title", widget: "string" }
          - {
              label: "Oorsprong tekst",
              name: "origin_text",
              widget: "markdown",
            }
          - { label: "Fundamenten", name: "fundamenten", widget: "markdown" }
          - { label: "Case studies", name: "case_studies", widget: "markdown" }
          - { label: "Redenen titel", name: "redenen_titel", widget: "string" }
          - label: "Redenen"
            name: "redenen"
            widget: "list"
            field: { label: "Reden", name: "reden", widget: "string" }
          - label: "Doelstellingen"
            name: "doelstellingen"
            widget: "list"
            field:
              { label: "Doelstelling", name: "doelstelling", widget: "string" }
          - label: "Praktisch"
            name: "praktisch"
            widget: "list"
            fields:
              - { label: "Titel", name: "titel", widget: "string" }
              - { label: "Uitleg", name: "uitleg", widget: "markdown" }
          - {
              label: "Uitleg betaling en inschrijving",
              name: "betaling_en_inschrijving",
              widget: "markdown",
            }
          - { label: "Laatste maand", name: "is_late", widget: "boolean" }
          - {
              label: "Rekening nummer",
              name: "rekeningnummer",
              widget: "string",
            }
          - { label: "Vermelding", name: "vermelding", widget: "string" }
          - { label: "Annulatie uitleg", name: "annulatie", widget: "markdown" }
          - { label: "Appendix", name: "appendix", widget: "markdown" }
