backend:
  name: git-gateway
  branch: main

media_folder: "images"

collections:
  - name: "content"
    label: "Website Content"
    files:
      - name: "content"
        label: "Main Content"
        file: "_data/content.yml"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Introductie tekst", name: "what_is_hat", widget: "markdown" }
          - { label: "Oorsprong titel", name: "origin_title", widget: "string" }
          - { label: "Oorsprong tekst", name: "origin_text", widget: "markdown" }
          - { label: "Fundamenten", name: "fundamenten", widget: "markdown" }
          - label: "Redenen"
            name: "redenen"
            widget: "list"
            field: { label: "Reden", name: "reden", widget: "string" }
          - label: "Doelstellingen"
            name: "doelstellingen"
            widget: "list"
            field: { label: "Doelstelling", name: "doelstelling", widget: "string" }
