backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"

local_backend: true

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "wat is HAT", name: "what-is-hat", widget: "markdown" }
